import h from 'snabbdom/h'
import R from 'ramda'
import pretty from 'pretty-js'

const code = json => h('pre.mono.bg-grey.p2.small', pretty(json))

const isEmpty = obj => !R.toPairs(obj).length 

const none = _ => h('p.mono.grey.p2.m0', 'None')


const listGroup = (title, obj) => {
  if(isEmpty(obj)) return ''
  return h('div', [
    h('p.mb0', `${title}:`)
  , h('ul.mt1', R.map(a => h('li.small.mono', `${String(a[0])}: ${String(a[1])}`), R.toPairs(obj)))
  ])
}

const formatDefault = (resp, a) => {
 if(resp.defaults[a[0]]) {
    let x = {}
    x[[a[0]]] = resp.defaults[a[0]] 
    return x
  }
  return ''
}

const paramsTable = resp =>  {
  if(isEmpty(resp.params)) return none() 
  return h('table.fullWidth', R.map(a => 
    h('tr', [
      h('td.p2.mono', String(a[0]))
    , h('td.p2', [
        String(a[1])
      , listGroup('Validations', resp.validations[a[0]])
      , listGroup('Defaults', formatDefault(resp, a))
      ])
    ])
  , R.toPairs(resp.params)))
}

const simpleRow = arr =>
  h('tr', [
    h('td.p2.mono', String(arr[0]))
  , h('td.p2', String(arr[1]))
  ])

const simpleTable = obj => {
  if(isEmpty(obj)) return none() 
  return h('table.fullWidth', R.map(a => 
    simpleRow(a)
  , R.toPairs(obj)))
}

const landingPage = _ =>
  h('article.pl2.col-right.pb3', [
    h('p.p2.bg-blue--light', 'Welcome to the CommitChange API')
  , h('p.mt3', 'These docs are automatically generated by calling the HTTP OPTIONS method on all of the  API resources.') 
  ])
  
module.exports = state  => {
  if(!state.selectedLink$()) return landingPage() 
  const {parent, meth, path} = state.selectedLink$()
  const currentRes = state.resources$()[parent][meth][path]
  return h('article.pl2.col-right.pb3', [
    h('h4.mono.m0.bg-blue--light.p2', 
        `${state.selectedLink$().meth} ${state.selectedLink$().parent + state.selectedLink$().path}`)
  , currentRes.description ? h('p.mb0.mt3', currentRes.description) : ''
  , h('hr')
  , h('h4', 'Params')
  , paramsTable(currentRes)
  , h('h4', 'Selectable')
  , simpleTable(currentRes.selectable)
  ])
}


